language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - mysql

before_script:
  - composer install --dev --no-interaction
  - cp tests/config.ini.travis tests/config.ini

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
