language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql

before_script:
  - cp tests/config.ini.travis tests/config.ini

script:
  - phpunit --bootstrap ./tests/bootstrap.php ./tests/
